# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 23:17
from __future__ import unicode_literals

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='vidcraftavatar.png', upload_to='', validators=[accounts.validators.validate_file_extension])),
                ('title', models.CharField(blank=True, max_length=115)),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateField(auto_now=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
