# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 19:14
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='thumbnail',
            field=models.FileField(default='vthumbnail.jpg', upload_to='thumbnails', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
