# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170401_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='mp4video'),
        ),
    ]
