# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 22:18
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170401_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='videomodel',
            name='input_video',
            field=models.FileField(blank=True, upload_to='mp4video'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.FileField(default='vidcraftavatar.png', upload_to='', validators=[accounts.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.VideoModel'),
        ),
    ]
