# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20170423_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='liked',
            new_name='likes',
        ),
    ]
