# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_sharemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
