# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0012_auto_20170429_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='videos.ShareModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
