# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_sharecommentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecommentmodel',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sharecomments', to='videos.ShareModel'),
        ),
    ]
