# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:45
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20170503_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.VideoModel'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='mp4video', validators=[accounts.validators.validate_file_video_extension]),
        ),
    ]
