# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_categorymodel_playlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='video',
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='video',
            field=models.ManyToManyField(related_name='playlistvideos', to='videos.VideoModel'),
        ),
    ]
