# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_auto_20170515_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='video',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.CategoryModel'),
        ),
    ]
