# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_auto_20170515_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
