# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0021_commentmodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='likedcmt',
            field=models.ManyToManyField(blank=True, related_name='likedcmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
