# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_commentmodel_likedcmt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='categoryname',
        ),
    ]
