# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_auto_20170515_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='GenreModel',
        ),
        migrations.RenameField(
            model_name='genremodel',
            old_name='categoryname',
            new_name='genrename',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='category',
            new_name='genre',
        ),
    ]
