# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_auto_20170515_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
