# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 16:10
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_auto_20170515_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='playlistimg',
            field=models.FileField(default='vidcraftavatar.png', upload_to='', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
