# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_playlistmodel_playlistimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.CommentModel'),
        ),
    ]
