# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_auto_20170517_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='is a reply?'),
        ),
    ]
