# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_commentmodel_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlistuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
