# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_auto_20170524_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmodel',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='playlistvideos', to='videos.VideoModel'),
        ),
    ]
