# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_auto_20170524_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
