# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_playlistmodel_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='playlistmodel',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sharecommentmodel',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sharemodel',
            old_name='shared_date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='videomodel',
            old_name='added_date',
            new_name='timestamp',
        ),
    ]
