# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_auto_20170531_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharemodel',
            old_name='timestamp',
            new_name='shared_date',
        ),
    ]
