# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_auto_20170531_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharemodel',
            old_name='shared_date',
            new_name='timestamp',
        ),
    ]
