# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_auto_20170531_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='playlistimg',
        ),
    ]
