# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0043_auto_20170619_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='genremodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='videos.GenreModel'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='mp4video'),
        ),
    ]
