# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0044_auto_20170626_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='genremodel',
            name='is_category',
            field=models.BooleanField(default=False, verbose_name='is a category?'),
        ),
    ]
