# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 03:10
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_genremodel_is_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='input_video',
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video',
            field=models.FileField(upload_to='mp4video', validators=[accounts.validators.validate_file_video_extension]),
        ),
    ]
