# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0047_auto_20170704_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='genrename',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
