# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='zipcode',
            field=models.CharField(default=11239, max_length=5),
            preserve_default=False,
        ),
    ]
