# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170916_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
