# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:53
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.FileField(default='vidcraftavatar.png', upload_to='', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
