# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:31
from __future__ import unicode_literals

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170320_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_banner',
            field=models.FileField(default='vidcraftavatar.png', upload_to='', validators=[accounts.validators.validate_file_extension]),
        ),
    ]
