# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_banner',
            new_name='profile_banner',
        ),
    ]
