# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='friend',
            new_name='friends',
        ),
    ]
