# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usermessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='joindate',
            new_name='timestamp',
        ),
    ]
