# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170727_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
