# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170810_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='usermessages',
            name='sender',
        ),
        migrations.DeleteModel(
            name='UserMessages',
        ),
    ]
